// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTotalClicksAndDownloads = `-- name: GetTotalClicksAndDownloads :one
SELECT
COALESCE(COUNT(hashed_ip) FILTER (WHERE event_type = 'click'), 0)::bigint AS total_clicks,
COALESCE(COUNT(hashed_ip) FILTER (WHERE event_type = 'download'), 0)::bigint AS total_downloads
FROM events
`

type GetTotalClicksAndDownloadsRow struct {
	TotalClicks    int64 `json:"total_clicks"`
	TotalDownloads int64 `json:"total_downloads"`
}

func (q *Queries) GetTotalClicksAndDownloads(ctx context.Context) (GetTotalClicksAndDownloadsRow, error) {
	row := q.db.QueryRow(ctx, getTotalClicksAndDownloads)
	var i GetTotalClicksAndDownloadsRow
	err := row.Scan(&i.TotalClicks, &i.TotalDownloads)
	return i, err
}

const storeEvent = `-- name: StoreEvent :exec
INSERT INTO events (cheatsheet_id, event_type, pathname, hashed_ip)
VALUES ($1, $2, $3, $4)
`

type StoreEventParams struct {
	CheatsheetID pgtype.UUID `json:"cheatsheet_id"`
	EventType    EventType   `json:"event_type"`
	Pathname     string      `json:"pathname"`
	HashedIp     string      `json:"hashed_ip"`
}

func (q *Queries) StoreEvent(ctx context.Context, arg StoreEventParams) error {
	_, err := q.db.Exec(ctx, storeEvent,
		arg.CheatsheetID,
		arg.EventType,
		arg.Pathname,
		arg.HashedIp,
	)
	return err
}
