// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pageviews.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBrowsersSummaryByDay = `-- name: GetBrowsersSummaryByDay :many
SELECT 
   DISTINCT(browser), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
  AND DATE_TRUNC('day', viewed_at)::date >= (NOW() - make_interval(days => $1::int))::date
  AND DATE_TRUNC('day', viewed_at)::date <= NOW()::date
GROUP BY browser
ORDER BY views DESC
`

type GetBrowsersSummaryByDayRow struct {
	Browser        pgtype.Text `json:"browser"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetBrowsersSummaryByDay(ctx context.Context, days int32) ([]GetBrowsersSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getBrowsersSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBrowsersSummaryByDayRow{}
	for rows.Next() {
		var i GetBrowsersSummaryByDayRow
		if err := rows.Scan(&i.Browser, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBrowsersSummaryForLast24Hours = `-- name: GetBrowsersSummaryForLast24Hours :many
SELECT 
   DISTINCT(browser), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
  AND viewed_at >= NOW() - INTERVAL '23 hours'
GROUP BY browser
ORDER BY views DESC
`

type GetBrowsersSummaryForLast24HoursRow struct {
	Browser        pgtype.Text `json:"browser"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetBrowsersSummaryForLast24Hours(ctx context.Context) ([]GetBrowsersSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getBrowsersSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBrowsersSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetBrowsersSummaryForLast24HoursRow
		if err := rows.Scan(&i.Browser, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountriesSummaryByDay = `-- name: GetCountriesSummaryByDay :many
SELECT 
   DISTINCT(country), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
 AND DATE_TRUNC('day', viewed_at)::date >= (NOW() - make_interval(days => $1::int))::date
 AND DATE_TRUNC('day', viewed_at)::date <= NOW()::date
GROUP BY country
ORDER BY views DESC
`

type GetCountriesSummaryByDayRow struct {
	Country        pgtype.Text `json:"country"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetCountriesSummaryByDay(ctx context.Context, days int32) ([]GetCountriesSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getCountriesSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCountriesSummaryByDayRow{}
	for rows.Next() {
		var i GetCountriesSummaryByDayRow
		if err := rows.Scan(&i.Country, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCountriesSummaryForLast24Hours = `-- name: GetCountriesSummaryForLast24Hours :many
SELECT 
   DISTINCT(country), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
 AND viewed_at >= NOW() - INTERVAL '23 hours'
GROUP BY country
ORDER BY views DESC
`

type GetCountriesSummaryForLast24HoursRow struct {
	Country        pgtype.Text `json:"country"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetCountriesSummaryForLast24Hours(ctx context.Context) ([]GetCountriesSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getCountriesSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCountriesSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetCountriesSummaryForLast24HoursRow
		if err := rows.Scan(&i.Country, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesSummaryByDay = `-- name: GetDevicesSummaryByDay :many
SELECT 
  d::date AS date,
  -- Mobile
  COALESCE(COUNT(p.viewed_at) FILTER (WHERE p.device = 'mobile'), 0)::bigint AS mobile_views,
  COALESCE(COUNT(DISTINCT p.hashed_ip) FILTER (WHERE p.device = 'mobile'), 0)::bigint AS mobile_visitors,
  -- Desktop
  COALESCE(COUNT(p.viewed_at) FILTER (WHERE p.device = 'desktop'), 0)::bigint AS desktop_views,
  COALESCE(COUNT(DISTINCT p.hashed_ip) FILTER (WHERE p.device = 'desktop'), 0)::bigint AS desktop_visitors
FROM generate_series(
    (NOW() - make_interval(days => $1::int))::date,
    NOW()::date,
    '1 day'
) AS d
LEFT JOIN pageviews p
  ON DATE_TRUNC('day', p.viewed_at)::date = d
  AND p.browser != 'Headless Chrome'
GROUP BY d
ORDER BY d
`

type GetDevicesSummaryByDayRow struct {
	Date            pgtype.Date `json:"date"`
	MobileViews     int64       `json:"mobile_views"`
	MobileVisitors  int64       `json:"mobile_visitors"`
	DesktopViews    int64       `json:"desktop_views"`
	DesktopVisitors int64       `json:"desktop_visitors"`
}

func (q *Queries) GetDevicesSummaryByDay(ctx context.Context, days int32) ([]GetDevicesSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getDevicesSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDevicesSummaryByDayRow{}
	for rows.Next() {
		var i GetDevicesSummaryByDayRow
		if err := rows.Scan(
			&i.Date,
			&i.MobileViews,
			&i.MobileVisitors,
			&i.DesktopViews,
			&i.DesktopVisitors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDevicesSummaryForLast24Hours = `-- name: GetDevicesSummaryForLast24Hours :many
SELECT 
  h::timestamp AS hour,
  -- Mobile
  COALESCE(COUNT(p.viewed_at) FILTER (WHERE p.device = 'mobile'), 0)::bigint AS mobile_views,
  COALESCE(COUNT(DISTINCT p.hashed_ip) FILTER (WHERE p.device = 'mobile'), 0)::bigint AS mobile_visitors,
  -- Desktop
  COALESCE(COUNT(p.viewed_at) FILTER (WHERE p.device = 'desktop'), 0)::bigint AS desktop_views,
  COALESCE(COUNT(DISTINCT p.hashed_ip) FILTER (WHERE p.device = 'desktop'), 0)::bigint AS desktop_visitors
FROM generate_series(
     date_trunc('hour', NOW() - INTERVAL '23 hours'),
    date_trunc('hour', NOW()),
    '1 hour'
) AS h
LEFT JOIN pageviews p
  ON DATE_TRUNC('hour', p.viewed_at)::timestamp = h
  AND p.browser != 'Headless Chrome'
GROUP BY h
ORDER BY h
`

type GetDevicesSummaryForLast24HoursRow struct {
	Hour            pgtype.Timestamp `json:"hour"`
	MobileViews     int64            `json:"mobile_views"`
	MobileVisitors  int64            `json:"mobile_visitors"`
	DesktopViews    int64            `json:"desktop_views"`
	DesktopVisitors int64            `json:"desktop_visitors"`
}

func (q *Queries) GetDevicesSummaryForLast24Hours(ctx context.Context) ([]GetDevicesSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getDevicesSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDevicesSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetDevicesSummaryForLast24HoursRow
		if err := rows.Scan(
			&i.Hour,
			&i.MobileViews,
			&i.MobileVisitors,
			&i.DesktopViews,
			&i.DesktopVisitors,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsTimeseriesByDay = `-- name: GetMetricsTimeseriesByDay :many
SELECT 
    d::date AS date,
    COALESCE(COUNT(p.viewed_at), 0)::bigint AS views,
    COALESCE(COUNT(DISTINCT p.hashed_ip), 0)::bigint AS unique_visitors
FROM generate_series(
    (NOW() - make_interval(days => $1::int))::date,
    NOW()::date,
    '1 day'
) AS d
LEFT JOIN pageviews p
    ON DATE_TRUNC('day', p.viewed_at)::date = d
    AND p.browser != 'Headless Chrome'
GROUP BY d
ORDER BY d
`

type GetMetricsTimeseriesByDayRow struct {
	Date           pgtype.Date `json:"date"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetMetricsTimeseriesByDay(ctx context.Context, days int32) ([]GetMetricsTimeseriesByDayRow, error) {
	rows, err := q.db.Query(ctx, getMetricsTimeseriesByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMetricsTimeseriesByDayRow{}
	for rows.Next() {
		var i GetMetricsTimeseriesByDayRow
		if err := rows.Scan(&i.Date, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMetricsTimeseriesForLast24Hours = `-- name: GetMetricsTimeseriesForLast24Hours :many
SELECT 
    h::timestamp AS hour,
    COALESCE(COUNT(p.viewed_at), 0)::bigint AS views,
    COALESCE(COUNT(DISTINCT p.hashed_ip), 0)::bigint AS unique_visitors
FROM generate_series(
    date_trunc('hour', NOW() - INTERVAL '23 hours'),
    date_trunc('hour', NOW()),
    '1 hour'
) AS h
LEFT JOIN pageviews p
    ON date_trunc('hour', p.viewed_at) = h
    AND p.browser != 'Headless Chrome'
GROUP BY h
ORDER BY h
`

type GetMetricsTimeseriesForLast24HoursRow struct {
	Hour           pgtype.Timestamp `json:"hour"`
	Views          int64            `json:"views"`
	UniqueVisitors int64            `json:"unique_visitors"`
}

func (q *Queries) GetMetricsTimeseriesForLast24Hours(ctx context.Context) ([]GetMetricsTimeseriesForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getMetricsTimeseriesForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMetricsTimeseriesForLast24HoursRow{}
	for rows.Next() {
		var i GetMetricsTimeseriesForLast24HoursRow
		if err := rows.Scan(&i.Hour, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSSummaryByDay = `-- name: GetOSSummaryByDay :many
SELECT 
   CASE 
      -- iOS variants
      WHEN os ILIKE '%iPhone OS%' OR os ILIKE '%iOS%' THEN 'iOS'::varchar
      -- Android variants
      WHEN os ILIKE '%Android%' THEN 'Android'::varchar
      -- Windows variants
      WHEN os ILIKE '%Windows%' THEN 'Windows'::varchar
      -- Mac OS variants
      WHEN os ILIKE '%Mac OS%' AND os NOT ILIKE '%iPhone%' THEN 'Mac OS'::varchar
      -- Linux variants
      WHEN os ILIKE '%Linux%' AND os NOT ILIKE '%Android%' THEN 'Linux'::varchar
      -- Chrome OS
      WHEN os ILIKE '%Chrome OS%' THEN 'Chrome OS'::varchar
      -- Keep other OS as-is or mark as Other
      ELSE COALESCE(os, 'Other')::varchar
   END AS os_group,
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
  AND DATE_TRUNC('day', viewed_at)::date >= (NOW() - make_interval(days => $1::int))::date
  AND DATE_TRUNC('day', viewed_at)::date <= NOW()::date
  AND os IS NOT NULL
GROUP BY os_group
ORDER BY views DESC
`

type GetOSSummaryByDayRow struct {
	OsGroup        string `json:"os_group"`
	Views          int64  `json:"views"`
	UniqueVisitors int64  `json:"unique_visitors"`
}

func (q *Queries) GetOSSummaryByDay(ctx context.Context, days int32) ([]GetOSSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getOSSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOSSummaryByDayRow{}
	for rows.Next() {
		var i GetOSSummaryByDayRow
		if err := rows.Scan(&i.OsGroup, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOSSummaryForLast24Hours = `-- name: GetOSSummaryForLast24Hours :many
SELECT 
   CASE 
      -- iOS variants
      WHEN os ILIKE '%iPhone OS%' OR os ILIKE '%iOS%' THEN 'iOS'::varchar
      -- Android variants
      WHEN os ILIKE '%Android%' THEN 'Android'::varchar
      -- Windows variants
      WHEN os ILIKE '%Windows%' THEN 'Windows'::varchar
      -- Mac OS variants
      WHEN os ILIKE '%Mac OS%' AND os NOT ILIKE '%iPhone%' THEN 'Mac OS'::varchar
      -- Linux variants
      WHEN os ILIKE '%Linux%' AND os NOT ILIKE '%Android%' THEN 'Linux'::varchar
      -- Chrome OS
      WHEN os ILIKE '%Chrome OS%' THEN 'Chrome OS'::varchar
      -- Keep other OS as-is or mark as Other
      ELSE COALESCE(os, 'Other')::varchar
   END AS os_group,
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
  AND viewed_at >= NOW() - INTERVAL '23 hours'
  AND os IS NOT NULL
GROUP BY os_group
ORDER BY views DESC
`

type GetOSSummaryForLast24HoursRow struct {
	OsGroup        string `json:"os_group"`
	Views          int64  `json:"views"`
	UniqueVisitors int64  `json:"unique_visitors"`
}

func (q *Queries) GetOSSummaryForLast24Hours(ctx context.Context) ([]GetOSSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getOSSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOSSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetOSSummaryForLast24HoursRow
		if err := rows.Scan(&i.OsGroup, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferrerSummaryByDay = `-- name: GetReferrerSummaryByDay :many
SELECT 
   DISTINCT(referrer), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
  AND DATE_TRUNC('day', viewed_at)::date >= (NOW() - make_interval(days => $1::int))::date
  AND DATE_TRUNC('day', viewed_at)::date <= NOW()::date
  AND referrer IS NOT NULL
GROUP BY referrer
ORDER BY views DESC
`

type GetReferrerSummaryByDayRow struct {
	Referrer       pgtype.Text `json:"referrer"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetReferrerSummaryByDay(ctx context.Context, days int32) ([]GetReferrerSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getReferrerSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReferrerSummaryByDayRow{}
	for rows.Next() {
		var i GetReferrerSummaryByDayRow
		if err := rows.Scan(&i.Referrer, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReferrerSummaryForLast24Hours = `-- name: GetReferrerSummaryForLast24Hours :many
SELECT 
   DISTINCT(referrer), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
 AND viewed_at >= NOW() - INTERVAL '23 hours'
 AND referrer IS NOT NULL
GROUP BY referrer
ORDER BY views DESC
`

type GetReferrerSummaryForLast24HoursRow struct {
	Referrer       pgtype.Text `json:"referrer"`
	Views          int64       `json:"views"`
	UniqueVisitors int64       `json:"unique_visitors"`
}

func (q *Queries) GetReferrerSummaryForLast24Hours(ctx context.Context) ([]GetReferrerSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getReferrerSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReferrerSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetReferrerSummaryForLast24HoursRow
		if err := rows.Scan(&i.Referrer, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutesSummaryByDay = `-- name: GetRoutesSummaryByDay :many
SELECT 
   DISTINCT(pathname), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
 AND DATE_TRUNC('day', viewed_at)::date >= (NOW() - make_interval(days => $1::int))::date
 AND DATE_TRUNC('day', viewed_at)::date <= NOW()::date
GROUP BY pathname
ORDER BY views DESC
`

type GetRoutesSummaryByDayRow struct {
	Pathname       string `json:"pathname"`
	Views          int64  `json:"views"`
	UniqueVisitors int64  `json:"unique_visitors"`
}

func (q *Queries) GetRoutesSummaryByDay(ctx context.Context, days int32) ([]GetRoutesSummaryByDayRow, error) {
	rows, err := q.db.Query(ctx, getRoutesSummaryByDay, days)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoutesSummaryByDayRow{}
	for rows.Next() {
		var i GetRoutesSummaryByDayRow
		if err := rows.Scan(&i.Pathname, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoutesSummaryForLast24Hours = `-- name: GetRoutesSummaryForLast24Hours :many
SELECT 
   DISTINCT(pathname), 
   COALESCE(COUNT(viewed_at), 0)::bigint AS views,
   COALESCE(COUNT(DISTINCT hashed_ip), 0)::bigint AS unique_visitors
FROM pageviews 
WHERE browser != 'Headless Chrome'
 AND viewed_at >= NOW() - INTERVAL '23 hours'
GROUP BY pathname
ORDER BY views DESC
`

type GetRoutesSummaryForLast24HoursRow struct {
	Pathname       string `json:"pathname"`
	Views          int64  `json:"views"`
	UniqueVisitors int64  `json:"unique_visitors"`
}

func (q *Queries) GetRoutesSummaryForLast24Hours(ctx context.Context) ([]GetRoutesSummaryForLast24HoursRow, error) {
	rows, err := q.db.Query(ctx, getRoutesSummaryForLast24Hours)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRoutesSummaryForLast24HoursRow{}
	for rows.Next() {
		var i GetRoutesSummaryForLast24HoursRow
		if err := rows.Scan(&i.Pathname, &i.Views, &i.UniqueVisitors); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalViewsAndVisitors = `-- name: GetTotalViewsAndVisitors :one
SELECT COUNT(id) as total_views, COUNT(DISTINCT hashed_ip) as total_visitors
FROM pageviews
`

type GetTotalViewsAndVisitorsRow struct {
	TotalViews    int64 `json:"total_views"`
	TotalVisitors int64 `json:"total_visitors"`
}

func (q *Queries) GetTotalViewsAndVisitors(ctx context.Context) (GetTotalViewsAndVisitorsRow, error) {
	row := q.db.QueryRow(ctx, getTotalViewsAndVisitors)
	var i GetTotalViewsAndVisitorsRow
	err := row.Scan(&i.TotalViews, &i.TotalVisitors)
	return i, err
}

const storePageview = `-- name: StorePageview :exec
INSERT INTO pageviews (pathname, hashed_ip, country, browser, os, device, user_agent, referrer)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type StorePageviewParams struct {
	Pathname  string      `json:"pathname"`
	HashedIp  string      `json:"hashed_ip"`
	Country   pgtype.Text `json:"country"`
	Browser   pgtype.Text `json:"browser"`
	Os        pgtype.Text `json:"os"`
	Device    pgtype.Text `json:"device"`
	UserAgent string      `json:"user_agent"`
	Referrer  pgtype.Text `json:"referrer"`
}

func (q *Queries) StorePageview(ctx context.Context, arg StorePageviewParams) error {
	_, err := q.db.Exec(ctx, storePageview,
		arg.Pathname,
		arg.HashedIp,
		arg.Country,
		arg.Browser,
		arg.Os,
		arg.Device,
		arg.UserAgent,
		arg.Referrer,
	)
	return err
}
