// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pageviews.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const storePageview = `-- name: StorePageview :exec
INSERT INTO pageviews (pathname, ip_address, user_agent, referrer)
VALUES ($1, $2, $3, $4)
`

type StorePageviewParams struct {
	Pathname  string      `json:"pathname"`
	IpAddress string      `json:"ip_address"`
	UserAgent string      `json:"user_agent"`
	Referrer  pgtype.Text `json:"referrer"`
}

func (q *Queries) StorePageview(ctx context.Context, arg StorePageviewParams) error {
	_, err := q.db.Exec(ctx, storePageview,
		arg.Pathname,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referrer,
	)
	return err
}
