// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCheatsheetsByCategoryAndSubcategory(ctx context.Context) ([]CountCheatsheetsByCategoryAndSubcategoryRow, error)
	CreateCheatsheet(ctx context.Context, arg CreateCheatsheetParams) error
	GetBrowsersSummaryByDay(ctx context.Context, days int32) ([]GetBrowsersSummaryByDayRow, error)
	GetBrowsersSummaryForLast24Hours(ctx context.Context) ([]GetBrowsersSummaryForLast24HoursRow, error)
	GetCategories(ctx context.Context) ([]string, error)
	GetCategoryDetails(ctx context.Context) ([]GetCategoryDetailsRow, error)
	GetCheatsheetByID(ctx context.Context, id pgtype.UUID) (GetCheatsheetByIDRow, error)
	GetCheatsheetBySlug(ctx context.Context, slug string) (GetCheatsheetBySlugRow, error)
	GetDevicesSummaryByDay(ctx context.Context, days int32) ([]GetDevicesSummaryByDayRow, error)
	GetDevicesSummaryForLast24Hours(ctx context.Context) ([]GetDevicesSummaryForLast24HoursRow, error)
	GetMetricsTimeseriesByDay(ctx context.Context, days int32) ([]GetMetricsTimeseriesByDayRow, error)
	GetMetricsTimeseriesForLast24Hours(ctx context.Context) ([]GetMetricsTimeseriesForLast24HoursRow, error)
	GetOSSummaryByDay(ctx context.Context, days int32) ([]GetOSSummaryByDayRow, error)
	GetOSSummaryForLast24Hours(ctx context.Context) ([]GetOSSummaryForLast24HoursRow, error)
	GetReferrerSummaryByDay(ctx context.Context, days int32) ([]GetReferrerSummaryByDayRow, error)
	GetReferrerSummaryForLast24Hours(ctx context.Context) ([]GetReferrerSummaryForLast24HoursRow, error)
	GetSubcategories(ctx context.Context) ([]string, error)
	GetTotalCheasheetsCount(ctx context.Context) (int64, error)
	GetTotalImageSize(ctx context.Context) (GetTotalImageSizeRow, error)
	GetTotalViewsAndVisitors(ctx context.Context) (GetTotalViewsAndVisitorsRow, error)
	ListCheatsheets(ctx context.Context, arg ListCheatsheetsParams) ([]ListCheatsheetsRow, error)
	StoreEvent(ctx context.Context, arg StoreEventParams) error
	StorePageview(ctx context.Context, arg StorePageviewParams) error
	UpdateCheatsheet(ctx context.Context, arg UpdateCheatsheetParams) error
}

var _ Querier = (*Queries)(nil)
