// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCheatsheet(ctx context.Context, arg CreateCheatsheetParams) error
	GetCheatsheetByID(ctx context.Context, id pgtype.UUID) (Cheatsheet, error)
	GetCheatsheetBySlug(ctx context.Context, slug string) (Cheatsheet, error)
	ListCheatsheets(ctx context.Context, arg ListCheatsheetsParams) ([]Cheatsheet, error)
	StoreEvent(ctx context.Context, arg StoreEventParams) error
	StorePageview(ctx context.Context, arg StorePageviewParams) error
	UpdateCheatsheet(ctx context.Context, arg UpdateCheatsheetParams) error
}

var _ Querier = (*Queries)(nil)
